"""DCSS item and artifact data constants."""

from __future__ import annotations

from .generated_dcss_data import (
    DCSS_ARMOUR_SLOTS,
    DCSS_ITEM_FLAVOUR_TEXT,
    DCSS_UNRANDART_NAMES,
)

RANGED_WEAPONS = {
    "sling",
    "shortbow",
    "longbow",
    "arbalest",
    "hand cannon",
    "triple crossbow",
}

WEAPON_BRANDS = {
    "flaming",
    "flame",
    "freezing",
    "freeze",
    "venom",
    "draining",
    "drain",
    "heavy",
    "speed",
    "antimagic",
    "holy",
    "holy wrath",
    "electrocution",
    "elec",
    "pain",
    "vampirism",
    "protection",
    "protect",
    "spectral",
    "reaping",
    "distortion",
    "chaos",
    "penetration",
    "sunder",
    "shock",
    "anguish",
    "deathbane",
}

SHIELD_ITEMS = {"buckler", "kite shield", "tower shield", "shield"}

HELMET_ITEMS = {"helmet", "hat"}

BOOTS_ITEMS = {"boots", "pair of boots", "barding"}

GLOVES_ITEMS = {"gloves", "pair of gloves"}

CLOAK_ITEMS = {"cloak", "scarf"}

BODY_ARMOUR_MARKERS = (
    "robe",
    "animal skin",
    "leather armour",
    "ring mail",
    "scale mail",
    "chain mail",
    "plate armour",
    "crystal plate armour",
    "troll leather armour",
    "steam dragon scales",
    "acid dragon scales",
    "swamp dragon scales",
    "fire dragon scales",
    "ice dragon scales",
    "pearl dragon scales",
    "storm dragon scales",
    "gold dragon scales",
    "shadow dragon scales",
    "quicksilver dragon scales",
    "hide armour",
    "skin",
)

BASE_SUBTYPE_ATTRIBUTES = {
    "ring of protection": {"AC"},
    "ring of evasion": {"EV"},
    "ring of strength": {"Str"},
    "ring of intelligence": {"Int"},
    "ring of dexterity": {"Dex"},
    "ring of magical power": {"MP"},
    "ring of willpower": {"Will"},
    "ring of protection from fire": {"rF"},
    "ring of protection from cold": {"rC"},
    "ring of poison resistance": {"rPois"},
    "ring of resist corrosion": {"rCorr"},
    "ring of see invisible": {"SInv"},
    "ring of wizardry": {"Wiz"},
    "amulet of reflection": {"Reflect", "SH"},
    "amulet of regeneration": {"Regen"},
    "amulet of magic regeneration": {"RegenMP"},
    "amulet of guardian spirit": {"Spirit"},
    "amulet of the acrobat": {"Acrobat"},
    "amulet of faith": {"Faith"},
    "amulet of dissipation": {"Dissipate"},
    "staff of alchemy": {"Alch", "rPois"},
    "staff of air": {"Air", "rElec"},
    "staff of cold": {"Ice", "rC"},
    "staff of conjuration": {"Conj"},
    "staff of death": {"Necro", "rN"},
    "staff of earth": {"Earth"},
    "staff of fire": {"Fire", "rF"},
    "staff of poison": {"Alch", "rPois"},
}

BASE_ITEM_ATTRIBUTES = {
    "troll leather armour": ["Regen+"],
    "troll skin": ["Regen+"],
}

UNRANDART_NAMES = {
    "Singing Sword",
    "Wrath of Trog",
    "mace of Variability",
    "partisan of Prune",
    "sword of Power",
    "staff of Olgreb",
    "crystal ball of Wucad Mu",
    "Vampire's Tooth",
    "scythe of Curses",
    "sceptre of Torment",
    "sword of Zonguldrok",
    "sword of Cerebov",
    "orb of Dispater",
    "sceptre of Asmodeus",
    "faerie dragon scales",
    'demon blade "Bloodbane"',
    "scimitar of Flaming Death",
    'eveningstar "Brilliance"',
    'demon blade "Leech"',
    "dagger of Chilly Death",
    'dagger "Morg"',
    'scythe "Finisher"',
    'greatsling "Punk"',
    'longbow "Zephyr"',
    'giant club "Skullcrusher"',
    "glaive of the Guard",
    "zealot's sword",
    'arbalest "Damnation"',
    "sword of the Dread Knight",
    'morningstar "Eos"',
    "spear of the Botono",
    "trident of the Octopus King",
    'mithril axe "Arga"',
    "Elemental Staff",
    'heavy crossbow "Sniper"',
    'longbow "Piercer"',
    "blowgun of the Assassin",
    'lance "Wyrmbane"',
    "Spriggan's Knife",
    "plutonium sword",
    'great mace "Undeadhunter"',
    'whip "Snakebite"',
    "knife of Accuracy",
    "Lehudib's crystal spear",
    "captain's cutlass",
    "storm bow",
    "tower shield of Ignorance",
    "robe of Augmentation",
    "cloak of the Thief",
    'tower shield "Bullseye"',
    "crown of Dyrovepreva",
    "hat of the Bear Spirit",
    "robe of Misfortune",
    "cloak of Flash",
    "hood of the Assassin",
    "Lear's hauberk",
    "skin of Zhor",
    "salamander hide armour",
    "gauntlets of War",
    "shield of Resistance",
    "robe of Folly",
    "Maxwell's patent armour",
    "mask of the Dragon",
    "robe of Night",
    "scales of the Dragon King",
    "hat of the Alchemist",
    "fencer's gloves",
    "cloak of Starlight",
    "ratskin cloak",
    "shield of the Gong",
    "amulet of the Air",
    "ring of Shadows",
    "amulet of Cekugob",
    "amulet of Tranquility",
    "necklace of Bloodlust",
    "ring of the Hare",
    "ring of the Tortoise",
    "ring of the Mage",
    "brooch of Shielding",
    "robe of Clouds",
    "hat of Pondering",
    "obsidian axe",
    "lightning scales",
    "Black Knight's barding",
    "amulet of Vitality",
    "autumn katana",
    'shillelagh "Devastator"',
    "dragonskin cloak",
    "ring of the Octopus King",
    "Axe of Woe",
    "moon troll leather armour",
    "macabre finger necklace",
    "boots of the spider",
    "dark maul",
    "hat of the High Council",
    "arc blade",
    'demon whip "Spellbinder"',
    "lajatang of Order",
    'great mace "Firestarter"',
    "orange crystal plate armour",
    "Majin-Bo",
    'pair of quick blades "Gyre" and "Gimble"',
    "Maxwell's etheric cage",
    "crown of Eternal Torment",
    "robe of Vines",
    "Kryia's mail coat",
    'frozen axe "Frostbite"',
    "armour of Talos",
    "warlock's mirror",
    "amulet of invisibility",
    "Maxwell's thermic engine",
    'demon trident "Rift"',
    "sphere of Battle",
    "Cigotuvi's embrace",
    "seven-league boots",
    "Mad Mage's Maulers",
    "dreamshard necklace",
    "Delatra's gloves",
    "woodcutter's axe",
    "Throatcutter",
    "staff of the Meek",
    'trishula "Condemnation"',
    "amulet of Elemental Vulnerability",
    "mountain boots",
    "Lochaber axe",
    "Hermit's Pendant",
    "slick slippers",
    "Force Lance",
    "consecrated labrys",
    'toga "Victory"',
    "Storm Queen's Shield",
    "dreamdust necklace",
    'hand cannon "Mule"',
    "gloves of the gadgeteer",
    "Charlatan's Orb",
    "justicar's regalia",
    "skull of Zonguldrok",
    "fungal fisticloak",
    "crown of vainglory",
    "scarf of invisibility",
    "swamp witch's dragon scales",
    'athame "Fimbulwinter"',
    "fire dragon occultist's scales",
    "ice dragon arcanist's scales",
}

UNRANDART_NAME_KEYS = {
    " ".join(name.casefold().split()) for name in UNRANDART_NAMES
}

# Source: crawl/crawl 092a145782, crawl-ref/source/dat/descript/items.txt and unrand.txt.
# These are the item description bodies shown by DCSS, keyed by normalized item name.
ITEM_FLAVOUR_TEXT = {
    "acid dragon scales": "The scales of an acid dragon. Although it does not provide its wearer with as much protection as the armour made from the scales of some larger dragons, it is somewhat lighter and less encumbering. It is also remarkably smooth, letting corrosive slime flow off it like water.",
    "amulet of chemistry": "An amulet which allows the wearer to extract small amounts of magical energy from any potion they drink and also enhances the power of their alchemy spells. The magic restoration effect requires the amulet to attune itself to the wearer's body while their reserves of magic are full.",
    "amulet of dissipation": "An amulet which causes magic contamination and negative status effects upon the wearer to expire twice as quickly with time.",
    "amulet of faith": "A charm crafted to call the attention of the gods to its wearer. This divine attention makes it easier to please your god, but your god will also take more notice of your transgressions. The amulet will drain some of your divine favour when removed.",
    "amulet of guardian spirit": "An amulet containing a protective spirit which will cause any damage taken to be divided between the wearer's reserves of health and magic.",
    "amulet of magic regeneration": "An amulet that increases the wearer's rate of magic regeneration. In order to function, it must first attune itself to the wearer's body with full reserves of magic.",
    "amulet of nothing": "An amulet with no special properties.",
    "amulet of reflection": "An amulet which improves its wearer's ability to shield against attacks. If no shield is worn, the force the amulet emits can serve as a weak shield on its own. Regardless, any ranged attacks the wearer blocks will be reflected back toward the attacker.",
    "amulet of regeneration": "An amulet that increases the wearer's rate of health regeneration. In order to function, it must first attune itself to the wearer's body at full health.",
    "amulet of the acrobat": "An amulet that allows the user to tumble and roll to evade the blows of their enemies, but only while moving and waiting. While taking other actions (including climbing stairs) the amulet conveys no benefits.",
    "amulet of wildshape": "An amulet which improves its wearer's skill with Shapeshifting.",
    "arbalest": "A large piece of machinery used for firing bolts, braced with steel and cranked with a windlass. It takes some time to load and fire.",
    "battleaxe": "A large war axe with a formidable double-sided head.",
    "blade talisman": "A jagged cluster of blades, almost impossible to grasp without injury. Causes long, needle-thin blades to grow from the wearer's body, allowing them to perform rapid auxiliary melee attacks and even parry blows. Having so many fragments of metal inside one's body reduces the effectiveness of body armour, but Shapeshifting skill mitigates this effect as well as increases the damage dealt.",
    "broad axe": "An axe with langets, spikes, a lengthed haft and a single-bladed crescent head.",
    "buckler": "A small piece of wood and metal, to be strapped on one arm for defence.",
    "chain mail": "A suit of armour made entirely out of tiny metal rings.",
    "charlatan's orb": "This orb is the work of a master artificer, contracted to retrieve the orb, who valued their life more than their professional integrity. While this fake faithfully recreates the eerie glow and space-warping properties of the true orb, the power it grants is artificial and only accessible to skilled evokers.",
    "cloak": "A cloth cloak.",
    "crystal ball of wucad mu": "A sphere of flawless crystal, shaped by countless mantras. When one focuses upon it, the boundaries between 'self' and 'other' sometimes seem to blur.",
    "crystal plate armour": "An incredibly heavy but extremely effective suit of crystalline armour.",
    "dagger": "A double-edged fighting knife with a sharp point.",
    "death talisman": "A grey-black vessel, infused with dark power through a sickening ritual. Transforms the wearer into an undying offence against life itself. Foes struck by wearer's melee weapons or hands are weakened, slowed, and drained. The wearer can also heal themself by tormenting living foes nearby; Shapeshifting skill increases the amount healed. Further, the wearer resists cold, has enhanced willpower, and is immune to poison, miasma, negative energy, and torment. The wearer also gains some of the more dubious benefits of having an undead body. They are vulnerable to holy damage and Dispel Undead, and cannot consume potions.",
    "dire flail": "A flail with long spikes and a heavy head.",
    "dragon-blood talisman": "An intricate carving, inlaid with dragon tooth and scale.",
    "dragon-coil talisman": "An intricate carving, inlaid with dragon tooth and scale.",
    "eveningstar": "The opposite of a morningstar. A balanced mace with a long shaft and a metal head covered in lethal spikes.",
    "falchion": "A long single-edged sword with a slightly curved blade.",
    "fire dragon scales": "The scales of a fire-breathing dragon. It provides great protection from fire, while rendering its wearer more susceptible to cold.",
    "flail": "A mace with a short chain connecting the head to the haft.",
    "glaive": "A pole with a large, heavy blade on one end.",
    "gold dragon scales": "The scales of a golden dragon. It is much heavier than most dragon scale armours, and grants its wearer resistance to poison, fire and cold.",
    "golden dragon scales": "The scales of a golden dragon. It is much heavier than most dragon scale armours, and grants its wearer resistance to poison, fire and cold.",
    "granite talisman": "A heavy stone icon, bearing the countenance of some long-forgotten king or god. Transforms the wearer into a slow, stone statue. The wearer's stone body is immune to poison and miasma, and gains resistance to electricity, negative energy, and torment. Shapeshifting skill increases armour granted.",
    "great sword": "A sword with a very long, heavy blade and a long handle.",
    "halberd": "A polearm consisting of an axe blade topped with a spike, mounted on a long shaft.",
    "hand axe": "A small axe.",
    "hand cannon": "A machine that fires metal slugs via applied thaumaturgy. Some enchant their projectiles to fall forward instead of down, others bewitch the slugs with a fatal attraction to their targets. All are slow, loud, and blast out thick smoke with each shot.",
    "hat": "A cloth hat.",
    "helmet": "A piece of metal headgear.",
    "ice dragon scales": "The scales of a cold-breathing dragon. It provides great protection from cold, while rendering its wearer more susceptible to fire.",
    "inkwell talisman": "A small bottle filled with mystical ink. Transforms the wearer into a walking scroll whose body is tattooed with the knowledge of a hundred mages. Being an omnibus of magical techniques gives them increased skill with all spell schools, which improves with Shapeshifting skill, but the form's ability to channel such magic is limited, and it cannot cast spells above level 4. Its attacks are also very weak, but have a chance of restoring 1 MP when they hit.",
    "kite shield": "A piece of wood and metal, to be strapped on one arm for defence.",
    "lajatang": "A very rare and extremely effective weapon, featuring a pole with half-moon blades at both ends.",
    "leather armour": "A suit made from layers of tanned animal hide. It provides basic protection with almost no hindrance to spellcasting or stealthy movement.",
    "long sword": "A sword with a long, slashing blade.",
    "longbow": "A long, strong bow made of yew.",
    "mace": "A short club with a metal head.",
    "maw talisman": "A miniature, desiccated head of some ferocious and hopefully extinct creature. Transforms the wearer's midsection into a giant mouth, gnashing and ready to devour foes. This maw confers a powerful bite attack which scales additionally with the wearer's own strength and can devour slain creatures to temporariy increase one's regeneration. Unfortunately, it also confers such profound hunger that it can be difficult to pull oneself away from particularly appetising foes.",
    "morningstar": "A mace with a head covered in short spikes.",
    "orb": "A sphere of crystal, carried in place of a shield. Magic scintillates within its interior.",
    "orcbow": "A recurved bow, crudely crafted from troll-bone and warg hair. The cave orcs' use of archery, so unlike their surface-dwelling ancestors, shows the influence of their elvish allies.",
    "pair of boots": "A pair of boots. They are worn on the feet, and cover all but the largest hooves and talons.",
    "pair of gloves": "A pair of gloves. They are worn on the hands, and cover all but the largest claws.",
    "pearl dragon scales": "The nacreous scales of a pearl dragon. It grants its wearer resistance to negative energies.",
    "plate armour": "A full suit of solid metal plate: cuirass, pauldrons, vambraces, waist plate and greaves. It provides excellent protection.",
    "quarterstaff": "A sturdy wooden pole, meant for fighting.",
    "quicksilver dragon scales": "The scales of a quicksilver dragon. Although it does not provide its wearer with as much protection as the scales of some heavier dragons, it is somewhat lighter and less encumbering. The armour repels both attacks on the wearer's willpower and magical modification of itself - it cannot be enchanted.",
    "quill talisman": "A spiny trinket reminiscent of a cactus. Causes sharp quills to grow all over the wearer's body which may cause injury to anyone unwise enough to attack them in melee.",
    "rapier": "A slender, sharply pointed sword, with an uncommonly elegant design.",
    "ring mail": "A light leather suit reinforced with a covering of metal rings. It is protective in combat, but slightly uncomfortable due to the added weight.",
    "ring of dexterity": "A ring that increases the dexterity of its wearer.",
    "ring of evasion": "A ring that makes its wearer more capable of avoiding attacks.",
    "ring of flight": "A ring that grants its wearer flight.",
    "ring of intelligence": "A ring that increases the intelligence of its wearer.",
    "ring of magical power": "A ring that increases its wearer's reserves of magical power for so long as it is worn.",
    "ring of poison resistance": "A ring that protects its wearer from poison.",
    "ring of positive energy": "A ring that protects its wearer from the effects of negative energy.",
    "ring of protection": "A ring that protects its wearer from most sources of damage.",
    "ring of protection from cold": "A ring that protects its wearer from cold.",
    "ring of protection from fire": "A ring that protects its wearer from fire.",
    "ring of resist corrosion": "A ring that protects its wearer from the effects of acid and corrosion.",
    "ring of see invisible": "A ring that allows its wearer to see invisible things.",
    "ring of slaying": "A ring that increases the wearer's accuracy and damage with ranged weapons and melee attacks.",
    "ring of strength": "A ring that increases the strength of its wearer.",
    "ring of willpower": "A ring that increases its wearer's willpower, protecting against certain magical effects.",
    "ring of wizardry": "A ring that increases the success rate of its wearer's magical spells.",
    "robe": "A large, loose-fitting, wide-sleeved outer garment made of light cloth. It offers little protection against physical harm, but does not hinder evasion or spellcasting.",
    "scale mail": "A leather suit covered with metal plates attached to each other in overlapping rows to provide full protection, but at the cost of reduced freedom of movement.",
    "scarf": "A length of stylish fabric. At its creation, enchantments were woven into it, and as such it cannot accept further enchantment.",
    "scimitar": "A long sword with a wide, curved blade.",
    "serpent talisman": "A jade snake coiled around a fossilised egg. Transforms the wearer into an amphisbaena - a legendary two-headed serpent. It is capable of wearing two pieces of headgear at once and its powerful coils can wind around foes and crush them to death, but its cold blood leaves it susceptible to being slowed by cold attacks.",
    "short sword": "A personal stabbing weapon with a short grip.",
    "shortbow": "A curved piece of wood and string, for shooting arrows.",
    "skull of zonguldrok": "The skull of a legendary necromancer, seemingly parted from the rest of its body. When held, it seems disinclined to explain the precise circumstances of its ending up in this state, but offers no objection to others siphoning what considerable necromantic power still remains in its ancient bones.",
    "sling": "A piece of cloth and leather for launching stones, adequate for hunting small game like rabbits or goblins.",
    "spear": "A hunting weapon consisting of a wooden shaft with a pointed metal head fastened on one end.",
    "spider talisman": "A strange charm made from shed arachnid exoskeletons bound together with silk. Transforms the wearer into an agile jumping spider who can move swiftly towards foes and inflict grievous damage on any it catches unaware. It cannot be ensnared by webs, but its attacks can ensnare its enemies in them. It can also leap briskly away from many dangers.",
    "staff of air": "A staff that increases the power of air spells cast by its wielder, and insulates them from electricity. If the wielder is skilled in Evocations and Air Magic, they can shock those struck by it, dealing electrical damage which bypasses half of defenders' armour.",
    "staff of alchemy": "A staff that increases the power of alchemy spells cast by its wielder, and protects them from the effects of poison. If the wielder is skilled in Evocations and Alchemy, they can envenom those struck by it.",
    "staff of cold": "A staff that increases the power of ice spells cast by its wielder, and protects them from the effects of cold. If the wielder is skilled in Evocations and Ice Magic, they can freeze those struck by it.",
    "staff of conjuration": "A staff that increases the power of conjurations cast by its wielder. If the wielder is skilled in Evocations and Conjurations, they can blast those they strike with pure energy.",
    "staff of death": "A staff that increases the power of necromantic spells cast by its wielder, and protects them from negative energy. If the wielder is skilled in Evocations and Necromancy, they can inflict great pain on those living souls they strike, dealing negative energy damage which bypasses armour.",
    "staff of earth": "A staff that increases the power of earth spells cast by its wielder. If the wielder is skilled in Evocations and Earth magic, they can fracture the ground beneath those struck by it, dealing substantial damage - though much less to creatures which fly.",
    "staff of fire": "A staff that increases the power of fire spells cast by its wielder, and protects them from the effects of fire. If the wielder is skilled in Evocations and Fire Magic, they can burn those struck by it.",
    "staff of necromancy": "A staff that increases the power of necromantic spells cast by its wielder, and protects them from negative energy. If the wielder is skilled in Evocations and Necromancy, they can inflict great pain on those living souls they strike, dealing negative energy damage which bypasses armour.",
    "staff of poison": "A staff that increases the power of alchemy spells cast by its wielder, and protects them from the effects of poison. If the wielder is skilled in Evocations and Alchemy, they can envenom those struck by it.",
    "steam dragon scales": "The scales of a steam-breathing dragon. Unlike the scales of some larger dragons, it does not provide its wearer with much protection (beyond a resistance to scalding steam), but it is extremely light and supple.",
    "storm dragon scales": "The scales of a lightning-breathing dragon. It is heavier than most dragon scale armours, and gives its wearer resistance to electrical discharges.",
    "storm talisman": "Lightning trapped, impossibly, in a bottle. Lets the wearer walk through the air as a raging, lightning-filled tempest. The wearer's melee attacks are electrified and strike all adjacent foes. The wearer also flies, gains immunity to poison, miasma, petrification, constriction, and sticky flame, and also resists electricity. They can launch themselves as a lightning bolt, blasting through everything in their way.",
    "swamp dragon scales": "The scales of a swamp dragon. It confers resistance to poison on its wearer.",
    "talisman of death": "A grey-black vessel, infused with dark power through a sickening ritual. Transforms the wearer into an undying offence against life itself. Foes struck by wearer's melee weapons or hands are weakened, slowed, and drained. The wearer can also heal themself by tormenting living foes nearby; Shapeshifting skill increases the amount healed. Further, the wearer resists cold, has enhanced willpower, and is immune to poison, miasma, negative energy, and torment. The wearer also gains some of the more dubious benefits of having an undead body. They are vulnerable to holy damage and Dispel Undead, and cannot consume potions.",
    "tower shield": "A large piece of wood and metal, to be strapped on one arm for defence.",
    "trident": "A fishing spear improved with a longer shaft and a three-pronged metal head.",
    "triple crossbow": "A crossbow with three strings arranged in series to provide exceptional power, initially designed as a siege weapon and then scaled down. It takes a considerable amount of time to load and fire.",
    "triple sword": "A formidable weapon created by a master craftsman. The blade of the sword forks into three great razor-sharp edges.",
    "troll leather armour": "The stiff and knobbly skin of a troll. It magically regenerates its wearer's flesh, once attuned to the wearer's body at full health.",
    "war axe": "A military axe with a long haft and a single-bladed head.",
    "whip": "A long plaited strip of leather. Originally developed for use in disagreements with cattle, this simple weapon is now widely used to settle differences between all sorts of creatures.",
}

ITEM_FLAVOUR_TEXT = {**ITEM_FLAVOUR_TEXT, **DCSS_ITEM_FLAVOUR_TEXT}
UNRANDART_NAMES = UNRANDART_NAMES | DCSS_UNRANDART_NAMES
UNRANDART_NAME_KEYS = {
    " ".join(name.casefold().split()) for name in UNRANDART_NAMES
}

SHIELD_ITEMS = SHIELD_ITEMS | {
    name for name, slot in DCSS_ARMOUR_SLOTS.items() if slot == "offhand" and name != "orb"
}
HELMET_ITEMS = HELMET_ITEMS | {
    name for name, slot in DCSS_ARMOUR_SLOTS.items() if slot == "helmet"
}
BOOTS_ITEMS = BOOTS_ITEMS | {
    name for name, slot in DCSS_ARMOUR_SLOTS.items() if slot in {"boots", "barding"}
}
GLOVES_ITEMS = GLOVES_ITEMS | {
    name for name, slot in DCSS_ARMOUR_SLOTS.items() if slot == "gloves"
}
CLOAK_ITEMS = CLOAK_ITEMS | {
    name for name, slot in DCSS_ARMOUR_SLOTS.items() if slot == "cloak"
}
BODY_ARMOUR_MARKERS = tuple(
    sorted(
        set(BODY_ARMOUR_MARKERS)
        | {name for name, slot in DCSS_ARMOUR_SLOTS.items() if slot == "body_armour"}
    )
)
