"""Local tile path constants for artifact presentation."""

from __future__ import annotations

WEAPON_TILES = {
    "dagger": "/tiles/dagger.png",
    "hand axe": "/tiles/hand-axe.png",
    "war axe": "/tiles/war-axe.png",
    "battleaxe": "/tiles/battleaxe.png",
    "broad axe": "/tiles/broad-axe.png",
    "short sword": "/tiles/short-sword.png",
    "rapier": "/tiles/rapier.png",
    "long sword": "/tiles/long-sword.png",
    "falchion": "/tiles/falchion.png",
    "great sword": "/tiles/great-sword.png",
    "scimitar": "/tiles/scimitar.png",
    "triple sword": "/tiles/triple-sword.png",
    "spear": "/tiles/spear.png",
    "trident": "/tiles/trident.png",
    "halberd": "/tiles/halberd.png",
    "glaive": "/tiles/glaive.png",
    "quarterstaff": "/tiles/quarterstaff.png",
    "lajatang": "/tiles/lajatang.png",
    "mace": "/tiles/mace.png",
    "flail": "/tiles/flail.png",
    "morningstar": "/tiles/morningstar.png",
    "eveningstar": "/tiles/eveningstar.png",
    "dire flail": "/tiles/dire-flail.png",
    "whip": "/tiles/whip.png",
    "sling": "/tiles/sling.png",
    "shortbow": "/tiles/shortbow.png",
    "longbow": "/tiles/longbow.png",
    "orcbow": "/tiles/orcbow.png",
    "arbalest": "/tiles/arbalest.png",
    "hand cannon": "/tiles/hand-cannon.png",
    "triple crossbow": "/tiles/triple-crossbow.png",
}

ARMOUR_TILES = {
    "robe": "/tiles/robe.png",
    "leather armour": "/tiles/leather-armour.png",
    "ring mail": "/tiles/ring-mail.png",
    "scale mail": "/tiles/scale-mail.png",
    "chain mail": "/tiles/chain-mail.png",
    "plate armour": "/tiles/plate-armour.png",
    "crystal plate armour": "/tiles/crystal-plate-armour.png",
    "troll leather armour": "/tiles/troll-leather-armour.png",
    "troll skin": "/tiles/troll-leather-armour.png",
    "fire dragon scales": "/tiles/fire-dragon-scales.png",
    "ice dragon scales": "/tiles/ice-dragon-scales.png",
    "pearl dragon scales": "/tiles/pearl-dragon-scales.png",
    "storm dragon scales": "/tiles/storm-dragon-scales.png",
    "gold dragon scales": "/tiles/gold-dragon-scales.png",
    "quicksilver dragon scales": "/tiles/quicksilver-dragon-scales.png",
    "steam dragon scales": "/tiles/steam-dragon-scales.png",
    "swamp dragon scales": "/tiles/swamp-dragon-scales.png",
    "acid dragon scales": "/tiles/acid-dragon-scales.png",
    "cloak": "/tiles/cloak.png",
    "scarf": "/tiles/scarf.png",
    "boots": "/tiles/boots.png",
    "pair of boots": "/tiles/boots.png",
    "gloves": "/tiles/gloves.png",
    "pair of gloves": "/tiles/gloves.png",
    "hat": "/tiles/hat.png",
    "helmet": "/tiles/helmet.png",
    "buckler": "/tiles/buckler.png",
    "kite shield": "/tiles/kite-shield.png",
    "tower shield": "/tiles/tower-shield.png",
    "shield": "/tiles/kite-shield.png",
    "orb": "/tiles/orb.png",
}

TALISMAN_TILES = {
    "inkwell talisman": "/tiles/talisman-inkwell.png",
    "serpent talisman": "/tiles/talisman-serpent.png",
    "quill talisman": "/tiles/talisman-quill.png",
    "maw talisman": "/tiles/talisman-maw.png",
    "blade talisman": "/tiles/talisman-blade.png",
    "dragon-blood talisman": "/tiles/talisman-dragon.png",
    "death talisman": "/tiles/talisman-death.png",
    "storm talisman": "/tiles/talisman-storm.png",
    "spider talisman": "/tiles/talisman-spider.png",
    "statue talisman": "/tiles/talisman-statue.png",
}

MISC_TILES = {
    "skull": "/tiles/skull-of-zonguldrok.png",
    "charlatan's orb": "/tiles/charlatans-orb.png",
    "crystal ball": "/tiles/crystal-ball-wucad-mu.png",
}
