"""Generated DCSS item data from the official Crawl source tree."""

from __future__ import annotations

DCSS_UNRANDART_NAMES = {'Axe of Woe',
 "Black Knight's barding",
 "Charlatan's Orb",
 "Cigotuvi's embrace",
 "Delatra's gloves",
 'Elemental Staff',
 'Force Lance',
 "Hermit's Pendant",
 "Kryia's mail coat",
 "Lear's hauberk",
 "Lehudib's crystal spear",
 'Lochaber axe',
 "Mad Mage's Maulers",
 'Majin-Bo',
 "Maxwell's etheric cage",
 "Maxwell's patent armour",
 "Maxwell's thermic engine",
 'Singing Sword',
 "Spriggan's Knife",
 "Storm Queen's Shield",
 'Throatcutter',
 "Vampire's Tooth",
 'Wrath of Trog',
 'amulet of Cekugob',
 'amulet of Elemental Vulnerability',
 'amulet of Vitality',
 'amulet of invisibility',
 'amulet of the Air',
 'amulet of the Four Winds',
 'arbalest "Damnation"',
 'arc blade',
 'armour of Talos',
 'autumn katana',
 'blowgun of the Assassin',
 'boots of the spider',
 'brooch of Shielding',
 "captain's cutlass",
 'cloak of Flash',
 'cloak of Starlight',
 'cloak of the Thief',
 'consecrated labrys',
 'crown of Dyrovepreva',
 'crown of Eternal Torment',
 'crown of vainglory',
 'crystal ball of Wucad Mu',
 'dagger "Morg"',
 'dagger of Chilly Death',
 'dark maul',
 'demon blade "Bloodbane"',
 'demon blade "Leech"',
 'demon trident "Rift"',
 'demon whip "Spellbinder"',
 'dragonskin cloak',
 'dreamdust necklace',
 'dreamshard necklace',
 'eveningstar "Brilliance"',
 'faerie dragon scales',
 "fencer's gloves",
 'frozen axe "Frostbite"',
 'fungal fisticloak',
 'gauntlets of War',
 'giant club "Skullcrusher"',
 'glaive of Prune',
 'glaive of the Guard',
 'gloves of the gadgeteer',
 'great mace "Firestarter"',
 'great mace "Undeadhunter"',
 'greatsling "Punk"',
 'hand cannon "Mule"',
 'hat of Pondering',
 'hat of the Alchemist',
 'hat of the Bear Spirit',
 'hat of the High Council',
 'heavy crossbow "Sniper"',
 'hood of the Assassin',
 "justicar's regalia",
 'knife of Accuracy',
 'lajatang of Order',
 'lance "Wyrmbane"',
 'lightning scales',
 'longbow "Piercer"',
 'longbow "Zephyr"',
 'macabre finger necklace',
 'mace of Variability',
 'mask of the Dragon',
 'mithril axe "Arga"',
 'moon troll leather armour',
 'morningstar "Eos"',
 'mountain boots',
 'necklace of Bloodlust',
 'obsidian axe',
 'orange crystal plate armour',
 'orb of Dispater',
 'pair of quick blades "Gyre" and "Gimble"',
 'plutonium sword',
 'ratskin cloak',
 'ring of Shadows',
 'ring of the Hare',
 'ring of the Mage',
 'ring of the Octopus King',
 'ring of the Tortoise',
 'robe of Augmentation',
 'robe of Clouds',
 'robe of Folly',
 'robe of Misfortune',
 'robe of Night',
 'robe of Vines',
 'salamander hide armour',
 'scales of the Dragon King',
 'scarf of invisibility',
 'sceptre of Asmodeus',
 'sceptre of Torment',
 'scimitar of Flaming Death',
 'scythe "Finisher"',
 'scythe of Curses',
 'seven-league boots',
 'shield of Resistance',
 'shield of the Gong',
 'shillelagh "Devastator"',
 'skin of Zhor',
 'skull of Zonguldrok',
 'slick slippers',
 'spear of the Botono',
 'sphere of Battle',
 'staff of Olgreb',
 'staff of the Meek',
 'storm bow',
 'sword of Cerebov',
 'sword of Power',
 'sword of Zonguldrok',
 'sword of the Dread Knight',
 'toga "Victory"',
 'tower shield "Bullseye"',
 'tower shield of Ignorance',
 'trident of the Octopus King',
 'trishula "Condemnation"',
 "warlock's mirror",
 'whip "Snakebite"',
 "woodcutter's axe",
 "zealot's sword"}


DCSS_ARMOUR_SLOTS = {'animal skin': 'body_armour',
 'barding': 'barding',
 'boots': 'boots',
 'buckler': 'offhand',
 'cap': 'helmet',
 'centaur barding': 'barding',
 'chain mail': 'body_armour',
 'cloak': 'cloak',
 'crystal plate armour': 'body_armour',
 'gloves': 'gloves',
 'hat': 'helmet',
 'helmet': 'helmet',
 'kite shield': 'offhand',
 'leather armour': 'body_armour',
 'orb': 'offhand',
 'plate armour': 'body_armour',
 'ring mail': 'body_armour',
 'robe': 'body_armour',
 'scale mail': 'body_armour',
 'scarf': 'cloak',
 'tower shield': 'offhand',
 'troll leather armour': 'body_armour'}
