"""Static DCSS item data copied from the official Crawl source tree."""

from __future__ import annotations

DCSS_DATA_SOURCE_VERSION = "master"

DCSS_UNRANDART_NAMES = {'Axe of Woe',
 "Black Knight's barding",
 "Charlatan's Orb",
 "Cigotuvi's embrace",
 "Delatra's gloves",
 'Elemental Staff',
 'Force Lance',
 "Hermit's Pendant",
 "Kryia's mail coat",
 "Lear's hauberk",
 "Lehudib's crystal spear",
 'Lochaber axe',
 "Mad Mage's Maulers",
 'Majin-Bo',
 "Maxwell's etheric cage",
 "Maxwell's patent armour",
 "Maxwell's thermic engine",
 'Singing Sword',
 "Spriggan's Knife",
 "Storm Queen's Shield",
 'Throatcutter',
 "Vampire's Tooth",
 'Wrath of Trog',
 'amulet of Cekugob',
 'amulet of Elemental Vulnerability',
 'amulet of Tranquility',
 'amulet of Vitality',
 'amulet of invisibility',
 'amulet of the Air',
 'arbalest "Damnation"',
 'arc blade',
 'armour of Talos',
 'athame "Fimbulwinter"',
 'autumn katana',
 'blowgun of the Assassin',
 'boots of the spider',
 'brooch of Shielding',
 "captain's cutlass",
 'cloak of Flash',
 'cloak of Starlight',
 'cloak of the Thief',
 'consecrated labrys',
 'crown of Dyrovepreva',
 'crown of Eternal Torment',
 'crown of vainglory',
 'crystal ball of Wucad Mu',
 'dagger "Morg"',
 'dagger of Chilly Death',
 'dark maul',
 'demon blade "Bloodbane"',
 'demon blade "Leech"',
 'demon trident "Rift"',
 'demon whip "Spellbinder"',
 'dragonskin cloak',
 'dreamdust necklace',
 'dreamshard necklace',
 'eveningstar "Brilliance"',
 'faerie dragon scales',
 "fencer's gloves",
 "fire dragon occultist's scales",
 'frozen axe "Frostbite"',
 'fungal fisticloak',
 'gauntlets of War',
 'giant club "Skullcrusher"',
 'glaive of the Guard',
 'gloves of the gadgeteer',
 'great mace "Firestarter"',
 'great mace "Undeadhunter"',
 'greatsling "Punk"',
 'hand cannon "Mule"',
 'hat of Pondering',
 'hat of the Alchemist',
 'hat of the Bear Spirit',
 'hat of the High Council',
 'heavy crossbow "Sniper"',
 'hood of the Assassin',
 "ice dragon arcanist's scales",
 "justicar's regalia",
 'knife of Accuracy',
 'lajatang of Order',
 'lance "Wyrmbane"',
 'lightning scales',
 'longbow "Piercer"',
 'longbow "Zephyr"',
 'macabre finger necklace',
 'mace of Variability',
 'mask of the Dragon',
 'mithril axe "Arga"',
 'moon troll leather armour',
 'morningstar "Eos"',
 'mountain boots',
 'necklace of Bloodlust',
 'obsidian axe',
 'orange crystal plate armour',
 'orb of Dispater',
 'pair of quick blades "Gyre" and "Gimble"',
 'partisan of Prune',
 'plutonium sword',
 'ratskin cloak',
 'ring of Shadows',
 'ring of the Hare',
 'ring of the Mage',
 'ring of the Octopus King',
 'ring of the Tortoise',
 'robe of Augmentation',
 'robe of Clouds',
 'robe of Folly',
 'robe of Misfortune',
 'robe of Night',
 'robe of Vines',
 'salamander hide armour',
 'scales of the Dragon King',
 'scarf of invisibility',
 'sceptre of Asmodeus',
 'sceptre of Torment',
 'scimitar of Flaming Death',
 'scythe "Finisher"',
 'scythe of Curses',
 'seven-league boots',
 'shield of Resistance',
 'shield of the Gong',
 'shillelagh "Devastator"',
 'skin of Zhor',
 'skull of Zonguldrok',
 'slick slippers',
 'spear of the Botono',
 'sphere of Battle',
 'staff of Olgreb',
 'staff of the Meek',
 'storm bow',
 "swamp witch's dragon scales",
 'sword of Cerebov',
 'sword of Power',
 'sword of Zonguldrok',
 'sword of the Dread Knight',
 'toga "Victory"',
 'tower shield "Bullseye"',
 'tower shield of Ignorance',
 'trident of the Octopus King',
 'trishula "Condemnation"',
 "warlock's mirror",
 'whip "Snakebite"',
 "woodcutter's axe",
 "zealot's sword"}

DCSS_ARMOUR_STATS = {'acid dragon scales': {'ac': 6,
                        'ev_penalty': -50,
                        'fit_max': 'SIZE_GIANT',
                        'fit_min': 'SIZE_LITTLE',
                        'price': 400,
                        'slot': 'body_armour'},
 'animal skin': {'ac': 2,
                 'ev_penalty': 0,
                 'fit_max': 'SIZE_GIANT',
                 'fit_min': 'SIZE_LITTLE',
                 'price': 3,
                 'slot': 'body_armour'},
 'barding': {'ac': 4,
             'ev_penalty': -60,
             'fit_max': 'SIZE_LARGE',
             'fit_min': 'SIZE_MEDIUM',
             'price': 230,
             'slot': 'barding'},
 'boots': {'ac': 1,
           'ev_penalty': 0,
           'fit_max': 'SIZE_MEDIUM',
           'fit_min': 'SIZE_SMALL',
           'price': 45,
           'slot': 'boots'},
 'buckler': {'ac': 3,
             'ev_penalty': -50,
             'fit_max': 'SIZE_MEDIUM',
             'fit_min': 'SIZE_LITTLE',
             'price': 45,
             'slot': 'offhand'},
 'cap': {'ac': 0,
         'ev_penalty': 0,
         'fit_max': 'SIZE_LARGE',
         'fit_min': 'SIZE_LITTLE',
         'price': 45,
         'slot': 'helmet'},
 'centaur barding': {'ac': 4,
                     'ev_penalty': -60,
                     'fit_max': 'SIZE_LARGE',
                     'fit_min': 'SIZE_MEDIUM',
                     'price': 230,
                     'slot': 'barding'},
 'chain mail': {'ac': 8,
                'ev_penalty': -140,
                'fit_max': 'SIZE_MEDIUM',
                'fit_min': 'SIZE_SMALL',
                'price': 60,
                'slot': 'body_armour'},
 'cloak': {'ac': 1,
           'ev_penalty': 0,
           'fit_max': 'SIZE_LARGE',
           'fit_min': 'SIZE_LITTLE',
           'price': 45,
           'slot': 'cloak'},
 'crystal plate armour': {'ac': 14,
                          'ev_penalty': -230,
                          'fit_max': 'SIZE_MEDIUM',
                          'fit_min': 'SIZE_SMALL',
                          'price': 600,
                          'slot': 'body_armour'},
 'fire dragon scales': {'ac': 8,
                        'ev_penalty': -90,
                        'fit_max': 'SIZE_GIANT',
                        'fit_min': 'SIZE_LITTLE',
                        'price': 500,
                        'slot': 'body_armour'},
 'gloves': {'ac': 1,
            'ev_penalty': 0,
            'fit_max': 'SIZE_MEDIUM',
            'fit_min': 'SIZE_SMALL',
            'price': 45,
            'slot': 'gloves'},
 'golden dragon scales': {'ac': 12,
                          'ev_penalty': -230,
                          'fit_max': 'SIZE_GIANT',
                          'fit_min': 'SIZE_LITTLE',
                          'price': 800,
                          'slot': 'body_armour'},
 'hat': {'ac': 0,
         'ev_penalty': 0,
         'fit_max': 'SIZE_LARGE',
         'fit_min': 'SIZE_TINY',
         'price': 40,
         'slot': 'helmet'},
 'helmet': {'ac': 1,
            'ev_penalty': 0,
            'fit_max': 'SIZE_MEDIUM',
            'fit_min': 'SIZE_SMALL',
            'price': 45,
            'slot': 'helmet'},
 'ice dragon scales': {'ac': 9,
                       'ev_penalty': -110,
                       'fit_max': 'SIZE_GIANT',
                       'fit_min': 'SIZE_LITTLE',
                       'price': 500,
                       'slot': 'body_armour'},
 'kite shield': {'ac': 8,
                 'ev_penalty': -100,
                 'fit_max': 'SIZE_LARGE',
                 'fit_min': 'SIZE_SMALL',
                 'price': 70,
                 'slot': 'offhand'},
 'leather armour': {'ac': 3,
                    'ev_penalty': -40,
                    'fit_max': 'SIZE_MEDIUM',
                    'fit_min': 'SIZE_SMALL',
                    'price': 20,
                    'slot': 'body_armour'},
 'orb': {'ac': 0,
         'ev_penalty': 0,
         'fit_max': 'SIZE_GIANT',
         'fit_min': 'SIZE_LITTLE',
         'price': 40,
         'slot': 'offhand'},
 'pearl dragon scales': {'ac': 10,
                         'ev_penalty': -110,
                         'fit_max': 'SIZE_GIANT',
                         'fit_min': 'SIZE_LITTLE',
                         'price': 1000,
                         'slot': 'body_armour'},
 'plate armour': {'ac': 10,
                  'ev_penalty': -180,
                  'fit_max': 'SIZE_MEDIUM',
                  'fit_min': 'SIZE_SMALL',
                  'price': 180,
                  'slot': 'body_armour'},
 'quicksilver dragon scales': {'ac': 9,
                               'ev_penalty': -70,
                               'fit_max': 'SIZE_GIANT',
                               'fit_min': 'SIZE_LITTLE',
                               'price': 500,
                               'slot': 'body_armour'},
 'ring mail': {'ac': 5,
               'ev_penalty': -70,
               'fit_max': 'SIZE_MEDIUM',
               'fit_min': 'SIZE_SMALL',
               'price': 40,
               'slot': 'body_armour'},
 'robe': {'ac': 2,
          'ev_penalty': 0,
          'fit_max': 'SIZE_LARGE',
          'fit_min': 'SIZE_LITTLE',
          'price': 9,
          'slot': 'body_armour'},
 'scale mail': {'ac': 6,
                'ev_penalty': -100,
                'fit_max': 'SIZE_MEDIUM',
                'fit_min': 'SIZE_SMALL',
                'price': 40,
                'slot': 'body_armour'},
 'scarf': {'ac': 0,
           'ev_penalty': 0,
           'fit_max': 'SIZE_LARGE',
           'fit_min': 'SIZE_LITTLE',
           'price': 50,
           'slot': 'cloak'},
 'shadow dragon scales': {'ac': 11,
                          'ev_penalty': -150,
                          'fit_max': 'SIZE_GIANT',
                          'fit_min': 'SIZE_LITTLE',
                          'price': 575,
                          'slot': 'body_armour'},
 'steam dragon scales': {'ac': 5,
                         'ev_penalty': 0,
                         'fit_max': 'SIZE_GIANT',
                         'fit_min': 'SIZE_LITTLE',
                         'price': 375,
                         'slot': 'body_armour'},
 'storm dragon scales': {'ac': 10,
                         'ev_penalty': -150,
                         'fit_max': 'SIZE_GIANT',
                         'fit_min': 'SIZE_LITTLE',
                         'price': 650,
                         'slot': 'body_armour'},
 'swamp dragon scales': {'ac': 7,
                         'ev_penalty': -70,
                         'fit_max': 'SIZE_GIANT',
                         'fit_min': 'SIZE_LITTLE',
                         'price': 450,
                         'slot': 'body_armour'},
 'tower shield': {'ac': 13,
                  'ev_penalty': -150,
                  'fit_max': 'SIZE_GIANT',
                  'fit_min': 'SIZE_MEDIUM',
                  'price': 80,
                  'slot': 'offhand'},
 'troll leather armour': {'ac': 3,
                          'ev_penalty': -40,
                          'fit_max': 'SIZE_GIANT',
                          'fit_min': 'SIZE_LITTLE',
                          'price': 150,
                          'slot': 'body_armour'}}

DCSS_ARMOUR_ATTRIBUTES = {'acid dragon scales': ['rCorr'],
 'fire dragon scales': ['rF++', 'rC-'],
 'golden dragon scales': ['rF+', 'rC+', 'rPois'],
 'ice dragon scales': ['rC++', 'rF-'],
 'pearl dragon scales': ['rN+'],
 'quicksilver dragon scales': ['Will+'],
 'shadow dragon scales': ['Stlth+'],
 'steam dragon scales': ['rSteam'],
 'storm dragon scales': ['rElec'],
 'swamp dragon scales': ['rPois'],
 'troll leather armour': ['Regen+']}

DCSS_ARMOUR_SLOTS = {'acid dragon scales': 'body_armour',
 'animal skin': 'body_armour',
 'barding': 'barding',
 'boots': 'boots',
 'buckler': 'offhand',
 'cap': 'helmet',
 'centaur barding': 'barding',
 'chain mail': 'body_armour',
 'cloak': 'cloak',
 'crystal plate armour': 'body_armour',
 'fire dragon scales': 'body_armour',
 'gloves': 'gloves',
 'golden dragon scales': 'body_armour',
 'hat': 'helmet',
 'helmet': 'helmet',
 'ice dragon scales': 'body_armour',
 'kite shield': 'offhand',
 'leather armour': 'body_armour',
 'orb': 'offhand',
 'pearl dragon scales': 'body_armour',
 'plate armour': 'body_armour',
 'quicksilver dragon scales': 'body_armour',
 'ring mail': 'body_armour',
 'robe': 'body_armour',
 'scale mail': 'body_armour',
 'scarf': 'cloak',
 'shadow dragon scales': 'body_armour',
 'steam dragon scales': 'body_armour',
 'storm dragon scales': 'body_armour',
 'swamp dragon scales': 'body_armour',
 'tower shield': 'offhand',
 'troll leather armour': 'body_armour'}

DCSS_WEAPON_STATS = {'arbalest': {'acquire_weight': 20,
              'commonness': 5,
              'damage': 16,
              'damage_type': 'DAMV_NON_MELEE',
              'hit': -2,
              'min_1h_size': 'NUM_SIZE_LEVELS',
              'min_2h_size': 'SIZE_LITTLE',
              'price': 75,
              'skill': 'ranged_weapons',
              'speed': 19},
 'athame': {'acquire_weight': 15,
            'commonness': 2,
            'damage': 6,
            'damage_type': 'DAMV_PIERCING',
            'hit': 5,
            'min_1h_size': 'SIZE_LITTLE',
            'min_2h_size': 'SIZE_LITTLE',
            'price': 100,
            'skill': 'short_blades',
            'speed': 13},
 'bardiche': {'acquire_weight': 25,
              'commonness': 1,
              'damage': 18,
              'damage_type': 'DAMV_CHOPPING',
              'hit': -6,
              'min_1h_size': 'NUM_SIZE_LEVELS',
              'min_2h_size': 'SIZE_MEDIUM',
              'price': 150,
              'skill': 'polearms',
              'speed': 19},
 'battleaxe': {'acquire_weight': 25,
               'commonness': 6,
               'damage': 15,
               'damage_type': 'DAMV_CHOPPING',
               'hit': -4,
               'min_1h_size': 'NUM_SIZE_LEVELS',
               'min_2h_size': 'SIZE_MEDIUM',
               'price': 100,
               'skill': 'axes',
               'speed': 17},
 'broad axe': {'acquire_weight': 25,
               'commonness': 4,
               'damage': 13,
               'damage_type': 'DAMV_CHOPPING',
               'hit': -2,
               'min_1h_size': 'SIZE_MEDIUM',
               'min_2h_size': 'SIZE_LITTLE',
               'price': 90,
               'skill': 'axes',
               'speed': 16},
 'club': {'acquire_weight': 0,
          'commonness': 10,
          'damage': 5,
          'damage_type': 'DAMV_CRUSHING',
          'hit': 3,
          'min_1h_size': 'SIZE_LITTLE',
          'min_2h_size': 'SIZE_LITTLE',
          'price': 5,
          'skill': 'maces_flails',
          'speed': 13},
 'dagger': {'acquire_weight': 40,
            'commonness': 10,
            'damage': 4,
            'damage_type': 'DAMV_PIERCING',
            'hit': 6,
            'min_1h_size': 'SIZE_LITTLE',
            'min_2h_size': 'SIZE_LITTLE',
            'price': 20,
            'skill': 'short_blades',
            'speed': 10},
 'demon blade': {'acquire_weight': 13,
                 'commonness': 0,
                 'damage': 13,
                 'damage_type': 'DAMV_SLICING',
                 'hit': -1,
                 'min_1h_size': 'SIZE_LITTLE',
                 'min_2h_size': 'SIZE_LITTLE',
                 'price': 250,
                 'skill': 'long_blades',
                 'speed': 13},
 'demon trident': {'acquire_weight': 25,
                   'commonness': 0,
                   'damage': 12,
                   'damage_type': 'DAMV_PIERCING',
                   'hit': 1,
                   'min_1h_size': 'SIZE_MEDIUM',
                   'min_2h_size': 'SIZE_LITTLE',
                   'price': 250,
                   'skill': 'polearms',
                   'speed': 13},
 'demon whip': {'acquire_weight': 13,
                'commonness': 0,
                'damage': 11,
                'damage_type': 'DAMV_SLASHING',
                'hit': 1,
                'min_1h_size': 'SIZE_LITTLE',
                'min_2h_size': 'SIZE_LITTLE',
                'price': 250,
                'skill': 'maces_flails',
                'speed': 11},
 'dire flail': {'acquire_weight': 20,
                'commonness': 2,
                'damage': 13,
                'damage_type': 'DAMV_CRUSHING | DAM_PIERCE',
                'hit': -3,
                'min_1h_size': 'NUM_SIZE_LEVELS',
                'min_2h_size': 'SIZE_MEDIUM',
                'price': 50,
                'skill': 'maces_flails',
                'speed': 13},
 'double sword': {'acquire_weight': 13,
                  'commonness': 0,
                  'damage': 15,
                  'damage_type': 'DAMV_SLICING',
                  'hit': -1,
                  'min_1h_size': 'SIZE_MEDIUM',
                  'min_2h_size': 'SIZE_LITTLE',
                  'price': 270,
                  'skill': 'long_blades',
                  'speed': 15},
 'eudemon blade': {'acquire_weight': 0,
                   'commonness': 0,
                   'damage': 14,
                   'damage_type': 'DAMV_SLICING',
                   'hit': -2,
                   'min_1h_size': 'SIZE_LITTLE',
                   'min_2h_size': 'SIZE_LITTLE',
                   'price': 300,
                   'skill': 'long_blades',
                   'speed': 12},
 'eveningstar': {'acquire_weight': 13,
                 'commonness': 0,
                 'damage': 15,
                 'damage_type': 'DAMV_CRUSHING | DAM_PIERCE',
                 'hit': -1,
                 'min_1h_size': 'SIZE_LITTLE',
                 'min_2h_size': 'SIZE_LITTLE',
                 'price': 270,
                 'skill': 'maces_flails',
                 'speed': 15},
 "executioner's axe": {'acquire_weight': 25,
                       'commonness': 0,
                       'damage': 18,
                       'damage_type': 'DAMV_CHOPPING',
                       'hit': -6,
                       'min_1h_size': 'NUM_SIZE_LEVELS',
                       'min_2h_size': 'SIZE_MEDIUM',
                       'price': 150,
                       'skill': 'axes',
                       'speed': 19},
 'falchion': {'acquire_weight': 0,
              'commonness': 7,
              'damage': 8,
              'damage_type': 'DAMV_SLICING',
              'hit': 2,
              'min_1h_size': 'SIZE_LITTLE',
              'min_2h_size': 'SIZE_LITTLE',
              'price': 30,
              'skill': 'long_blades',
              'speed': 13},
 'flail': {'acquire_weight': 10,
           'commonness': 8,
           'damage': 10,
           'damage_type': 'DAMV_CRUSHING',
           'hit': 0,
           'min_1h_size': 'SIZE_LITTLE',
           'min_2h_size': 'SIZE_LITTLE',
           'price': 35,
           'skill': 'maces_flails',
           'speed': 14},
 'giant club': {'acquire_weight': 25,
                'commonness': 1,
                'damage': 20,
                'damage_type': 'DAMV_CRUSHING',
                'hit': -6,
                'min_1h_size': 'NUM_SIZE_LEVELS',
                'min_2h_size': 'SIZE_LARGE',
                'price': 21,
                'skill': 'maces_flails',
                'speed': 16},
 'giant spiked club': {'acquire_weight': 25,
                       'commonness': 1,
                       'damage': 22,
                       'damage_type': 'DAMV_CRUSHING | DAM_PIERCE',
                       'hit': -7,
                       'min_1h_size': 'NUM_SIZE_LEVELS',
                       'min_2h_size': 'SIZE_LARGE',
                       'price': 26,
                       'skill': 'maces_flails',
                       'speed': 18},
 'glaive': {'acquire_weight': 15,
            'commonness': 5,
            'damage': 15,
            'damage_type': 'DAMV_CHOPPING',
            'hit': -3,
            'min_1h_size': 'NUM_SIZE_LEVELS',
            'min_2h_size': 'SIZE_MEDIUM',
            'price': 100,
            'skill': 'polearms',
            'speed': 17},
 'great mace': {'acquire_weight': 24,
                'commonness': 3,
                'damage': 17,
                'damage_type': 'DAMV_CRUSHING',
                'hit': -4,
                'min_1h_size': 'NUM_SIZE_LEVELS',
                'min_2h_size': 'SIZE_MEDIUM',
                'price': 100,
                'skill': 'maces_flails',
                'speed': 17},
 'great sword': {'acquire_weight': 20,
                 'commonness': 6,
                 'damage': 17,
                 'damage_type': 'DAMV_SLICING',
                 'hit': -3,
                 'min_1h_size': 'NUM_SIZE_LEVELS',
                 'min_2h_size': 'SIZE_MEDIUM',
                 'price': 100,
                 'skill': 'long_blades',
                 'speed': 17},
 'halberd': {'acquire_weight': 15,
             'commonness': 5,
             'damage': 13,
             'damage_type': 'DAMV_CHOPPING | DAM_PIERCE',
             'hit': -3,
             'min_1h_size': 'NUM_SIZE_LEVELS',
             'min_2h_size': 'SIZE_MEDIUM',
             'price': 40,
             'skill': 'polearms',
             'speed': 15},
 'hand axe': {'acquire_weight': 0,
              'commonness': 9,
              'damage': 7,
              'damage_type': 'DAMV_CHOPPING',
              'hit': 3,
              'min_1h_size': 'SIZE_LITTLE',
              'min_2h_size': 'SIZE_LITTLE',
              'price': 30,
              'skill': 'axes',
              'speed': 13},
 'hand cannon': {'acquire_weight': 24,
                 'commonness': 0,
                 'damage': 16,
                 'damage_type': 'DAMV_NON_MELEE',
                 'hit': 3,
                 'min_1h_size': 'SIZE_LITTLE',
                 'min_2h_size': 'SIZE_LITTLE',
                 'price': 270,
                 'skill': 'ranged_weapons',
                 'speed': 19},
 'lajatang': {'acquire_weight': 50,
              'commonness': 2,
              'damage': 16,
              'damage_type': 'DAMV_SLICING',
              'hit': -3,
              'min_1h_size': 'NUM_SIZE_LEVELS',
              'min_2h_size': 'SIZE_LITTLE',
              'price': 150,
              'skill': 'staves',
              'speed': 14},
 'long sword': {'acquire_weight': 10,
                'commonness': 7,
                'damage': 10,
                'damage_type': 'DAMV_SLICING',
                'hit': 1,
                'min_1h_size': 'SIZE_LITTLE',
                'min_2h_size': 'SIZE_LITTLE',
                'price': 35,
                'skill': 'long_blades',
                'speed': 14},
 'longbow': {'acquire_weight': 13,
             'commonness': 2,
             'damage': 14,
             'damage_type': 'DAMV_NON_MELEE',
             'hit': 0,
             'min_1h_size': 'NUM_SIZE_LEVELS',
             'min_2h_size': 'SIZE_MEDIUM',
             'price': 110,
             'skill': 'ranged_weapons',
             'speed': 17},
 'mace': {'acquire_weight': 0,
          'commonness': 9,
          'damage': 8,
          'damage_type': 'DAMV_CRUSHING',
          'hit': 3,
          'min_1h_size': 'SIZE_LITTLE',
          'min_2h_size': 'SIZE_LITTLE',
          'price': 30,
          'skill': 'maces_flails',
          'speed': 14},
 'morningstar': {'acquire_weight': 20,
                 'commonness': 7,
                 'damage': 13,
                 'damage_type': 'DAMV_CRUSHING | DAM_PIERCE',
                 'hit': -2,
                 'min_1h_size': 'SIZE_LITTLE',
                 'min_2h_size': 'SIZE_LITTLE',
                 'price': 60,
                 'skill': 'maces_flails',
                 'speed': 15},
 'orcbow': {'acquire_weight': 20,
            'commonness': 8,
            'damage': 11,
            'damage_type': 'DAMV_NON_MELEE',
            'hit': -3,
            'min_1h_size': 'NUM_SIZE_LEVELS',
            'min_2h_size': 'SIZE_LITTLE',
            'price': 40,
            'skill': 'ranged_weapons',
            'speed': 15},
 'partisan': {'acquire_weight': 25,
              'commonness': 3,
              'damage': 14,
              'damage_type': 'DAMV_PIERCING',
              'hit': 1,
              'min_1h_size': 'SIZE_MEDIUM',
              'min_2h_size': 'SIZE_LITTLE',
              'price': 70,
              'skill': 'polearms',
              'speed': 17},
 'quarterstaff': {'acquire_weight': 50,
                  'commonness': 8,
                  'damage': 10,
                  'damage_type': 'DAMV_CRUSHING',
                  'hit': 3,
                  'min_1h_size': 'NUM_SIZE_LEVELS',
                  'min_2h_size': 'SIZE_LITTLE',
                  'price': 50,
                  'skill': 'staves',
                  'speed': 13},
 'quick blade': {'acquire_weight': 25,
                 'commonness': 0,
                 'damage': 4,
                 'damage_type': 'DAMV_PIERCING',
                 'hit': 6,
                 'min_1h_size': 'SIZE_LITTLE',
                 'min_2h_size': 'SIZE_LITTLE',
                 'price': 250,
                 'skill': 'short_blades',
                 'speed': 15},
 'rapier': {'acquire_weight': 20,
            'commonness': 8,
            'damage': 7,
            'damage_type': 'DAMV_PIERCING',
            'hit': 4,
            'min_1h_size': 'SIZE_LITTLE',
            'min_2h_size': 'SIZE_LITTLE',
            'price': 55,
            'skill': 'short_blades',
            'speed': 12},
 'sacred scourge': {'acquire_weight': 0,
                    'commonness': 0,
                    'damage': 12,
                    'damage_type': 'DAMV_SLASHING',
                    'hit': 0,
                    'min_1h_size': 'SIZE_LITTLE',
                    'min_2h_size': 'SIZE_LITTLE',
                    'price': 300,
                    'skill': 'maces_flails',
                    'speed': 11},
 'scimitar': {'acquire_weight': 20,
              'commonness': 6,
              'damage': 12,
              'damage_type': 'DAMV_SLICING',
              'hit': 0,
              'min_1h_size': 'SIZE_LITTLE',
              'min_2h_size': 'SIZE_LITTLE',
              'price': 60,
              'skill': 'long_blades',
              'speed': 14},
 'short sword': {'acquire_weight': 0,
                 'commonness': 8,
                 'damage': 5,
                 'damage_type': 'DAMV_PIERCING',
                 'hit': 4,
                 'min_1h_size': 'SIZE_LITTLE',
                 'min_2h_size': 'SIZE_LITTLE',
                 'price': 30,
                 'skill': 'short_blades',
                 'speed': 10},
 'shortbow': {'acquire_weight': 0,
              'commonness': 8,
              'damage': 8,
              'damage_type': 'DAMV_NON_MELEE',
              'hit': 2,
              'min_1h_size': 'NUM_SIZE_LEVELS',
              'min_2h_size': 'SIZE_LITTLE',
              'price': 30,
              'skill': 'ranged_weapons',
              'speed': 14},
 'sling': {'acquire_weight': 10,
           'commonness': 8,
           'damage': 7,
           'damage_type': 'DAMV_NON_MELEE',
           'hit': 0,
           'min_1h_size': 'SIZE_LITTLE',
           'min_2h_size': 'SIZE_LITTLE',
           'price': 15,
           'skill': 'ranged_weapons',
           'speed': 14},
 'spear': {'acquire_weight': 0,
           'commonness': 8,
           'damage': 6,
           'damage_type': 'DAMV_PIERCING',
           'hit': 4,
           'min_1h_size': 'SIZE_LITTLE',
           'min_2h_size': 'SIZE_LITTLE',
           'price': 30,
           'skill': 'polearms',
           'speed': 11},
 'staff': {'acquire_weight': 0,
           'commonness': 0,
           'damage': 5,
           'damage_type': 'DAMV_CRUSHING',
           'hit': 5,
           'min_1h_size': 'SIZE_LITTLE',
           'min_2h_size': 'SIZE_LITTLE',
           'price': 15,
           'skill': 'staves',
           'speed': 12},
 'trident': {'acquire_weight': 20,
             'commonness': 6,
             'damage': 9,
             'damage_type': 'DAMV_PIERCING',
             'hit': 1,
             'min_1h_size': 'SIZE_MEDIUM',
             'min_2h_size': 'SIZE_LITTLE',
             'price': 35,
             'skill': 'polearms',
             'speed': 13},
 'triple crossbow': {'acquire_weight': 13,
                     'commonness': 0,
                     'damage': 23,
                     'damage_type': 'DAMV_NON_MELEE',
                     'hit': -2,
                     'min_1h_size': 'NUM_SIZE_LEVELS',
                     'min_2h_size': 'SIZE_SMALL',
                     'price': 200,
                     'skill': 'ranged_weapons',
                     'speed': 23},
 'triple sword': {'acquire_weight': 24,
                  'commonness': 0,
                  'damage': 19,
                  'damage_type': 'DAMV_SLICING',
                  'hit': -4,
                  'min_1h_size': 'NUM_SIZE_LEVELS',
                  'min_2h_size': 'SIZE_MEDIUM',
                  'price': 150,
                  'skill': 'long_blades',
                  'speed': 18},
 'trishula': {'acquire_weight': 0,
              'commonness': 0,
              'damage': 13,
              'damage_type': 'DAMV_PIERCING',
              'hit': 0,
              'min_1h_size': 'SIZE_MEDIUM',
              'min_2h_size': 'SIZE_LITTLE',
              'price': 300,
              'skill': 'polearms',
              'speed': 13},
 'war axe': {'acquire_weight': 25,
             'commonness': 7,
             'damage': 11,
             'damage_type': 'DAMV_CHOPPING',
             'hit': 0,
             'min_1h_size': 'SIZE_LITTLE',
             'min_2h_size': 'SIZE_LITTLE',
             'price': 35,
             'skill': 'axes',
             'speed': 15},
 'whip': {'acquire_weight': 0,
          'commonness': 4,
          'damage': 6,
          'damage_type': 'DAMV_SLASHING',
          'hit': 2,
          'min_1h_size': 'SIZE_LITTLE',
          'min_2h_size': 'SIZE_LITTLE',
          'price': 25,
          'skill': 'maces_flails',
          'speed': 11}}

DCSS_STAFF_STATS = {'air': {'ac_check': 'ac_type::half',
         'damage_mult': 50,
         'damage_type': 'BEAM_ELECTRICITY',
         'skill': 'air_magic'},
 'alchemy': {'ac_check': 'ac_type::normal',
             'damage_mult': 63,
             'damage_type': 'BEAM_POISON',
             'skill': 'alchemy'},
 'cold': {'ac_check': 'ac_type::normal',
          'damage_mult': 63,
          'damage_type': 'BEAM_COLD',
          'skill': 'ice_magic'},
 'conjuration': {'ac_check': 'ac_type::normal',
                 'damage_mult': 50,
                 'damage_type': 'BEAM_MMISSILE',
                 'skill': 'conjurations'},
 'earth': {'ac_check': 'ac_type::normal',
           'damage_mult': 63,
           'damage_type': 'BEAM_MMISSILE',
           'skill': 'earth_magic'},
 'fire': {'ac_check': 'ac_type::normal',
          'damage_mult': 63,
          'damage_type': 'BEAM_FIRE',
          'skill': 'fire_magic'},
 'necromancy': {'ac_check': 'ac_type::normal',
                'damage_mult': 63,
                'damage_type': 'BEAM_NEG',
                'skill': 'necromancy'}}

DCSS_MISSILE_STATS = {'arrow': {'damage': 0, 'mulch_rate': 1, 'price': 2},
 'bolt': {'damage': 0, 'mulch_rate': 1, 'price': 2},
 'boomerang': {'damage': 6, 'mulch_rate': 20, 'price': 20},
 'dart': {'damage': 0, 'mulch_rate': 12, 'price': 3},
 'javelin': {'damage': 10, 'mulch_rate': 20, 'price': 30},
 'large rock': {'damage': 20, 'mulch_rate': 25, 'price': 15},
 'needle': {'damage': 0, 'mulch_rate': 12, 'price': 2},
 'sling bullet': {'damage': 0, 'mulch_rate': 1, 'price': 5},
 'slug': {'damage': 0, 'mulch_rate': 1, 'price': 2},
 'stone': {'damage': 2, 'mulch_rate': 8, 'price': 1},
 'throwing net': {'damage': 0, 'mulch_rate': 0, 'price': 30}}
