"""Generate frontend mock artifacts from a player's remote morgue files."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from crawl_service.morgue.fetcher import (
    build_morgue_raw_texts,
    fetch_morgue_files,
    select_recent_morgue_files,
)
from crawl_service.processor import artifact_documents_from_raw_text
from crawl_service.worker import DEFAULT_MORGUE_BASE_URL
from api.presenter import present_artifact_document


DEFAULT_OUTPUT = ROOT / "frontend" / "src" / "data" / "mockArtifacts.ts"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Fetch recent morgue files, parse artifacts, and write frontend mock data."
    )
    parser.add_argument("--player", default="wiiwiwi")
    parser.add_argument("--limit", type=int, default=30)
    parser.add_argument("--base-url", default=DEFAULT_MORGUE_BASE_URL)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--delay", type=float, default=0.05)
    args = parser.parse_args()

    morgue_url = f"{args.base_url.rstrip('/')}/{args.player}/"
    files = select_recent_morgue_files(fetch_morgue_files(morgue_url), args.limit)
    raw_texts = build_morgue_raw_texts(files, delay=args.delay)

    documents = []
    for raw_text in raw_texts:
        documents.extend(
            present_artifact_document(document.to_dict()).model_dump()
            for document in artifact_documents_from_raw_text(raw_text)
        )

    documents.sort(
        key=lambda document: (
            document["score"]["total"],
            document["score"]["offense"],
            document["name"].casefold(),
        ),
        reverse=True,
    )

    output = _typescript_module(documents, args.player, files)
    args.output.write_text(output, encoding="utf-8")
    print(
        f"Wrote {len(documents)} artifacts from {len(files)} {args.player} files to {args.output}"
    )


def _typescript_module(documents: list[dict], player: str, files) -> str:
    file_names = ", ".join(file.name for file in files)
    json_text = json.dumps(documents, indent=2, ensure_ascii=False)
    return (
        "import type { Artifact } from '../types/artifact';\n\n"
        f"// Generated by scripts/generate_frontend_mock_artifacts.py from {player}'s "
        f"{len(files)} most recent morgue txt/lst files.\n"
        f"// Source files: {file_names}\n"
        f"export const mockArtifacts: Artifact[] = {json_text};\n"
    )


if __name__ == "__main__":
    main()
